<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'console.command_loader' shared service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\console\\CommandLoader\\CommandLoaderInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\console\\CommandLoader\\ContainerCommandLoader.php';

return $this->services['console.command_loader'] = new \Symfony\Component\Console\CommandLoader\ContainerCommandLoader(new \Symfony\Component\DependencyInjection\ServiceLocator(array('console.command.about' => function (): \Symfony\Bundle\FrameworkBundle\Command\AboutCommand {
    return ($this->privates['console.command.about'] ?? $this->load('getConsole_Command_AboutService.php'));
}, 'console.command.assets_install' => function (): \Symfony\Bundle\FrameworkBundle\Command\AssetsInstallCommand {
    return ($this->privates['console.command.assets_install'] ?? $this->load('getConsole_Command_AssetsInstallService.php'));
}, 'console.command.cache_clear' => function (): \Symfony\Bundle\FrameworkBundle\Command\CacheClearCommand {
    return ($this->privates['console.command.cache_clear'] ?? $this->load('getConsole_Command_CacheClearService.php'));
}, 'console.command.cache_pool_clear' => function (): \Symfony\Bundle\FrameworkBundle\Command\CachePoolClearCommand {
    return ($this->privates['console.command.cache_pool_clear'] ?? $this->load('getConsole_Command_CachePoolClearService.php'));
}, 'console.command.cache_pool_delete' => function (): \Symfony\Bundle\FrameworkBundle\Command\CachePoolDeleteCommand {
    return ($this->privates['console.command.cache_pool_delete'] ?? $this->load('getConsole_Command_CachePoolDeleteService.php'));
}, 'console.command.cache_pool_prune' => function (): \Symfony\Bundle\FrameworkBundle\Command\CachePoolPruneCommand {
    return ($this->privates['console.command.cache_pool_prune'] ?? $this->load('getConsole_Command_CachePoolPruneService.php'));
}, 'console.command.cache_warmup' => function (): \Symfony\Bundle\FrameworkBundle\Command\CacheWarmupCommand {
    return ($this->privates['console.command.cache_warmup'] ?? $this->load('getConsole_Command_CacheWarmupService.php'));
}, 'console.command.config_debug' => function (): \Symfony\Bundle\FrameworkBundle\Command\ConfigDebugCommand {
    return ($this->privates['console.command.config_debug'] ?? $this->load('getConsole_Command_ConfigDebugService.php'));
}, 'console.command.config_dump_reference' => function (): \Symfony\Bundle\FrameworkBundle\Command\ConfigDumpReferenceCommand {
    return ($this->privates['console.command.config_dump_reference'] ?? $this->load('getConsole_Command_ConfigDumpReferenceService.php'));
}, 'console.command.container_debug' => function (): \Symfony\Bundle\FrameworkBundle\Command\ContainerDebugCommand {
    return ($this->privates['console.command.container_debug'] ?? $this->load('getConsole_Command_ContainerDebugService.php'));
}, 'console.command.debug_autowiring' => function (): \Symfony\Bundle\FrameworkBundle\Command\DebugAutowiringCommand {
    return ($this->privates['console.command.debug_autowiring'] ?? $this->load('getConsole_Command_DebugAutowiringService.php'));
}, 'console.command.event_dispatcher_debug' => function (): \Symfony\Bundle\FrameworkBundle\Command\EventDispatcherDebugCommand {
    return ($this->privates['console.command.event_dispatcher_debug'] ?? $this->load('getConsole_Command_EventDispatcherDebugService.php'));
}, 'console.command.router_debug' => function (): \Symfony\Bundle\FrameworkBundle\Command\RouterDebugCommand {
    return ($this->privates['console.command.router_debug'] ?? $this->load('getConsole_Command_RouterDebugService.php'));
}, 'console.command.router_match' => function (): \Symfony\Bundle\FrameworkBundle\Command\RouterMatchCommand {
    return ($this->privates['console.command.router_match'] ?? $this->load('getConsole_Command_RouterMatchService.php'));
}, 'console.command.yaml_lint' => function (): \Symfony\Bundle\FrameworkBundle\Command\YamlLintCommand {
    return ($this->privates['console.command.yaml_lint'] ?? $this->load('getConsole_Command_YamlLintService.php'));
}, 'old_sound_rabbit_mq.anon_consumer_command' => function (): \OldSound\RabbitMqBundle\Command\AnonConsumerCommand {
    return ($this->privates['old_sound_rabbit_mq.anon_consumer_command'] ?? $this->load('getOldSoundRabbitMq_AnonConsumerCommandService.php'));
}, 'old_sound_rabbit_mq.batch_consumer_command' => function (): \OldSound\RabbitMqBundle\Command\BatchConsumerCommand {
    return ($this->privates['old_sound_rabbit_mq.batch_consumer_command'] ?? $this->load('getOldSoundRabbitMq_BatchConsumerCommandService.php'));
}, 'old_sound_rabbit_mq.command.rpc_server_command' => function (): \OldSound\RabbitMqBundle\Command\RpcServerCommand {
    return ($this->privates['old_sound_rabbit_mq.command.rpc_server_command'] ?? $this->load('getOldSoundRabbitMq_Command_RpcServerCommandService.php'));
}, 'old_sound_rabbit_mq.command.setup_fabric_command' => function (): \OldSound\RabbitMqBundle\Command\SetupFabricCommand {
    return ($this->privates['old_sound_rabbit_mq.command.setup_fabric_command'] ?? $this->load('getOldSoundRabbitMq_Command_SetupFabricCommandService.php'));
}, 'old_sound_rabbit_mq.command.std_in_producer_command' => function (): \OldSound\RabbitMqBundle\Command\StdInProducerCommand {
    return ($this->privates['old_sound_rabbit_mq.command.std_in_producer_command'] ?? $this->load('getOldSoundRabbitMq_Command_StdInProducerCommandService.php'));
}, 'old_sound_rabbit_mq.consumer_command' => function (): \OldSound\RabbitMqBundle\Command\ConsumerCommand {
    return ($this->privates['old_sound_rabbit_mq.consumer_command'] ?? $this->load('getOldSoundRabbitMq_ConsumerCommandService.php'));
}, 'old_sound_rabbit_mq.delete_command' => function (): \OldSound\RabbitMqBundle\Command\DeleteCommand {
    return ($this->privates['old_sound_rabbit_mq.delete_command'] ?? $this->load('getOldSoundRabbitMq_DeleteCommandService.php'));
}, 'old_sound_rabbit_mq.dynamic_consumer_command' => function (): \OldSound\RabbitMqBundle\Command\DynamicConsumerCommand {
    return ($this->privates['old_sound_rabbit_mq.dynamic_consumer_command'] ?? $this->load('getOldSoundRabbitMq_DynamicConsumerCommandService.php'));
}, 'old_sound_rabbit_mq.multiple_consumer_command' => function (): \OldSound\RabbitMqBundle\Command\MultipleConsumerCommand {
    return ($this->privates['old_sound_rabbit_mq.multiple_consumer_command'] ?? $this->load('getOldSoundRabbitMq_MultipleConsumerCommandService.php'));
}, 'old_sound_rabbit_mq.purge_consumer_command' => function (): \OldSound\RabbitMqBundle\Command\PurgeConsumerCommand {
    return ($this->privates['old_sound_rabbit_mq.purge_consumer_command'] ?? $this->load('getOldSoundRabbitMq_PurgeConsumerCommandService.php'));
}, 'swiftmailer.command.debug' => function (): \Symfony\Bundle\SwiftmailerBundle\Command\DebugCommand {
    return ($this->privates['swiftmailer.command.debug'] ?? $this->load('getSwiftmailer_Command_DebugService.php'));
}, 'swiftmailer.command.new_email' => function (): \Symfony\Bundle\SwiftmailerBundle\Command\NewEmailCommand {
    return ($this->privates['swiftmailer.command.new_email'] ?? $this->load('getSwiftmailer_Command_NewEmailService.php'));
}, 'swiftmailer.command.send_email' => function (): \Symfony\Bundle\SwiftmailerBundle\Command\SendEmailCommand {
    return ($this->privates['swiftmailer.command.send_email'] ?? $this->load('getSwiftmailer_Command_SendEmailService.php'));
})), array('about' => 'console.command.about', 'assets:install' => 'console.command.assets_install', 'cache:clear' => 'console.command.cache_clear', 'cache:pool:clear' => 'console.command.cache_pool_clear', 'cache:pool:prune' => 'console.command.cache_pool_prune', 'cache:pool:delete' => 'console.command.cache_pool_delete', 'cache:warmup' => 'console.command.cache_warmup', 'debug:config' => 'console.command.config_debug', 'config:dump-reference' => 'console.command.config_dump_reference', 'debug:container' => 'console.command.container_debug', 'debug:autowiring' => 'console.command.debug_autowiring', 'debug:event-dispatcher' => 'console.command.event_dispatcher_debug', 'debug:router' => 'console.command.router_debug', 'router:match' => 'console.command.router_match', 'lint:yaml' => 'console.command.yaml_lint', 'rabbitmq:anon-consumer' => 'old_sound_rabbit_mq.anon_consumer_command', 'rabbitmq:batch:consumer' => 'old_sound_rabbit_mq.batch_consumer_command', 'rabbitmq:consumer' => 'old_sound_rabbit_mq.consumer_command', 'rabbitmq:delete' => 'old_sound_rabbit_mq.delete_command', 'rabbitmq:dynamic-consumer' => 'old_sound_rabbit_mq.dynamic_consumer_command', 'rabbitmq:multiple-consumer' => 'old_sound_rabbit_mq.multiple_consumer_command', 'rabbitmq:purge' => 'old_sound_rabbit_mq.purge_consumer_command', 'rabbitmq:rpc-server' => 'old_sound_rabbit_mq.command.rpc_server_command', 'rabbitmq:setup-fabric' => 'old_sound_rabbit_mq.command.setup_fabric_command', 'rabbitmq:stdin-producer' => 'old_sound_rabbit_mq.command.std_in_producer_command', 'debug:swiftmailer' => 'swiftmailer.command.debug', 'swiftmailer:email:send' => 'swiftmailer.command.new_email', 'swiftmailer:spool:send' => 'swiftmailer.command.send_email'));
