old_sound_rabbit_mq:
    connections:
        default:
            host: '%rabbitmq_host%'
            user: '%rabbitmq_user%'
            password: '%rabbitmq_password%'
            vhost: '%rabbitmq_my_project_vhost%'
            connection_timeout: 60
            read_write_timeout: 60
            keepalive: false
            heartbeat: 30
    producers:
        emailing:
            connection: default
            exchange_options:
                name: emails
                type: direct
    consumers:
        emailing:
            connection:       default
            exchange_options: {name: 'emails', type: direct}
            queue_options:    {name: 'emails'}
            callback:         email_service