<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYuc5DbU\srcTestDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYuc5DbU/srcTestDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerYuc5DbU.legacy');

    return;
}

if (!\class_exists(srcTestDebugProjectContainer::class, false)) {
    \class_alias(\ContainerYuc5DbU\srcTestDebugProjectContainer::class, srcTestDebugProjectContainer::class, false);
}

return new \ContainerYuc5DbU\srcTestDebugProjectContainer(array(
    'container.build_hash' => 'Yuc5DbU',
    'container.build_id' => 'c5a8f836',
    'container.build_time' => 1538936180,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerYuc5DbU');
