<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLiGIofP\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLiGIofP/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerLiGIofP.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerLiGIofP\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerLiGIofP\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'LiGIofP',
    'container.build_id' => '97932f90',
    'container.build_time' => 1538908746,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerLiGIofP');
